#!/bin/bash
set -e

case "$1" in
    remove|deconfigure)
        # Ferma il servizio se è in esecuzione
        if [ -d /run/systemd/system ]; then
            systemctl stop neuroindex >/dev/null 2>&1 || true
            systemctl disable neuroindex >/dev/null 2>&1 || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
